

#define ACTIVE_MOTOR_1_CLK PA_ODR = 0
#define ACTIVE_MOTOR_2_CLK PA_ODR = 1
#define ACTIVE_MOTOR_3_CLK PA_ODR = 2
#define ACTIVE_MOTOR_4_CLK PA_ODR = 3
#define ACTIVE_OUT_SCK_CLK PA_ODR = 4
#define ACTIVE_FLASH_SCK_CLK PA_ODR = 5
#define ACTIVE_IN_SCK_CLK PA_ODR = 6
#define ACTIVE_RF_SCK_CLK PA_ODR = 7



void board_init(void);



